# PyTorch, Tensors, and Rubik's cubes

**The first thing we need to do (in order to use PyTorch) is make sure it's installed.**

In [3]:
import torch

**What is a tensor?** A tensor is a generalization of vectors and matrices. A vector is an order-1 tensor. A matrix is an order-2 tensor. You can think of a Rubik's cube as an order-3 tensor, where each block is a cell of the tensor. Let's first represent a Rubik's cube as an order-3 tensor using PyTorch.

In [4]:
import torch
RUBIKS_CUBE = torch.tensor([[[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]],
                    
                            [[10, 11, 12],
                             [13, 0, 14],
                             [15, 16, 17]],
                    
                            [[18, 19, 20],
                             [21, 22, 23],
                             [24, 25, 26]]])
print(RUBIKS_CUBE)


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13,  0, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


**You can imagine it as if the Rubik's cube is sitting on a table and we're looking at it top-down.** The first matrix are the 9 blocks we can see. The second matrix is the next layer down, and the third matrix is the layer of blocks closest to the table. We can use PyTorch to twist and flip the Rubik's cube using tensor manipulations.

What follows are a series of exercises for getting comfortable with using and manipulating tensors using PyTorch. The following tutorial is a useful starting point:

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

A more comprehensive set of tensor operations can be found here:

https://pytorch.org/docs/stable/torch.html

There are many ways to solve these exercises. Try to use them as an opportunity to explore the library, and see what methods you find convenient.

**Exercise 1:** Write a function ```encode``` in ```rubik.py``` that takes the current Rubik's cube and turns it into a string by "reading" each block (starting from the top layer) as the kth letter of the alphabet. Conveniently, there are exactly 26 blocks that we'll ever see (since the middle block always remains in the middle of the Rubik's cube). When encoding, ignore the middle block (with the value 0).

There's a unit test in ```test.py```, so that you can check your algorithm is working properly. Run it from the command line as follows:

    python -m unittest test.RubiksCubeTests.test_encode
    
Once it's working, the following code should produce the alphabet.

In [5]:
from rubik import encode, RUBIKS_CUBE

encode(RUBIKS_CUBE)

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

**Exercise 2:** Implement the function ```flip_away``` in ```rubik.py``` so that it takes the Rubik's cube and "flips" the Rubik's cube away from us (remember we're looking at it top-down, sitting on a table), so that the blocks we now see are the blocks we would have seen by crouching down and looking at the cube from the front. 

There's a unit test in ```test.py```, so that you can check your implementation is working properly. Run it from the command line as follows:

    python -m unittest test.RubiksCubeTests.test_flip_away
    
Once it's working, run the following code to flip your Rubik's cube away from you.

In [6]:
from rubik import flip_away, RUBIKS_CUBE

flip_away(RUBIKS_CUBE)

tensor([[[ 7,  8,  9],
         [15, 16, 17],
         [24, 25, 26]],

        [[ 4,  5,  6],
         [13,  0, 14],
         [21, 22, 23]],

        [[ 1,  2,  3],
         [10, 11, 12],
         [18, 19, 20]]])

**Exercise 3:**  Implement the function ```twist_right``` in ```rubik.py``` so that it twists the top layer of the Rubik's cube clockwise.

There's a unit test in ```test.py```, so that you can check your implementation is working properly. Run it from the command line as follows:

    python -m unittest test.RubiksCubeTests.test_twist_right
    
Once it's working, run the following code to twist your Rubik's cube to the right.

In [7]:
from rubik import twist_right, RUBIKS_CUBE

twist_right(RUBIKS_CUBE)

tensor([[[ 7,  4,  1],
         [ 8,  5,  2],
         [ 9,  6,  3]],

        [[10, 11, 12],
         [13,  0, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

**Exercise 4:** Implement the function ```rotate_right``` in ```rubik.py``` so that it takes the Rubik's cube and "rotates" the Rubik's cube to the right (remember we're looking at it top-down, sitting on a table), so that the blocks we now see are the same blocks we saw before, but rotated 90 degrees to the right.

There's a unit test in ```test.py```, so that you can check your implementation is working properly. Run it from the command line as follows:

    python -m unittest test.RubiksCubeTests.test_rotate_right
    
Once it's working, run the following code to rotate your Rubik's cube to the right.

In [8]:
from rubik import rotate_right, RUBIKS_CUBE

rotate_right(RUBIKS_CUBE)

tensor([[[ 7,  4,  1],
         [ 8,  5,  2],
         [ 9,  6,  3]],

        [[15, 13, 10],
         [16,  0, 11],
         [17, 14, 12]],

        [[24, 21, 18],
         [25, 22, 19],
         [26, 23, 20]]])

After all these functions are working, it will be time to do this.

In [10]:
from rubik import rotate_right, flip_away, twist_right, RUBIKS_CUBE

def answer():
    operations = [flip_away, rotate_right, rotate_right, rotate_right, twist_right,
                  twist_right, twist_right, twist_right, rotate_right, flip_away]
    result = RUBIKS_CUBE
    for op in operations:
        result = op(result)
    return encode(result)[7:11]

def submit(response):
    import rpyc
    c = rpyc.connect("134.10.103.248", 18861)
    return c.root.submit_response('q3', response)

print('You submit the password {} to the server.'.format(answer()))
submit(answer())

You submit the password STOP to the server.


'Correct!'

In [11]:
submit('GO')

'Incorrect response! Try again.'